#!/usr/bin/python3
#
# (C) Copyright 2020 Tillmann Heidsieck
#
# SPDX-License-Identifier: MIT
#
from datetime import datetime as date
import re
import subprocess

Import("env")

gitversion = subprocess.check_output(["git", "-C", env.subst("$SRC_DIR"),
                                      "describe", "--always", "--dirty"],
                                     shell=False).strip().decode()
repdict = {
    "VERSION" : gitversion,
    "BUILD_DATE" : date.now().strftime("%Y-%m-%d_%T"),
    "RELEASE" : False,
    "DEBUG" : False,
}

vc = ""
with open("misc/version.h.in") as f:
    vc = f.read()

for k in repdict.keys():
    if type(repdict[k]) == bool:
        vc = re.sub("(//)?(#define " + k + ") .*?", "\1" if repdict[k] else "//\1" , vc)
    else:
        vc = re.sub("@" + k + "@", repdict[k], vc)

# TODO WHY! do we need to create this include in the source directory?!
with open(env.subst("include/version.h"), "w") as f:
    f.write("/* This file is autogenerated, do not change it!\n * Change the template misc/version.h.in instead\n */\n\n\n" + vc)

if env.subst("$PIOENV") == "release" :
    m = re.match(r"(.*?)(-g[0-9a-f]{7})?(-dirty)?$", gitversion)
    if m and len(m.groups("")[2]) == 0:
        env.Replace(PROGNAME="firmware_%s" % m.groups()[0].replace("-", "."))
